print("assalamualaikum")
print("let me introduce my self")
name=input("my name is : muhammad irvan zaeni")
print("but you can call me")
name=input("nick name : irvan")
print("my npm is")
nim=input("nim : 312110024")
print("i was born in")
born=input("born : brebes")
print("and i am")
age=input("age : 22 years old")
print("i am very glad if you want to invitemy house in")
house=input("my house in : jatibarang brebes street")
print("so, don't forget to call me before with the number")
telp=input("telp : 08970090401")